ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |d|
    d.build_dir = "."
    d.has_ssh = true
    d.privileged = true
    d.create_args = ["-v", "/sys/fs/cgroup:/sys/fs/cgroup:ro"]
  end
end
