load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_go",
    urls = ["https://github.com/bazelbuild/rules_go/releases/download/0.18.3/rules_go-0.18.3.tar.gz"],
    sha256 = "86ae934bd4c43b99893fc64be9d9fc684b81461581df7ea8fc291c816f5ee8c5",
)

http_archive(
    name = "bazel_gazelle",
    urls = ["https://github.com/bazelbuild/bazel-gazelle/releases/download/0.17.0/bazel-gazelle-0.17.0.tar.gz"],
    sha256 = "3c681998538231a2d24d0c07ed5a7658cb72bfb5fd4bf9911157c0e9ac6a2687",
)


load("@io_bazel_rules_go//go:deps.bzl", "go_download_sdk", "go_rules_dependencies", "go_register_toolchains")
load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies", "go_repository")

go_download_sdk(
    name = "go_sdk",
    urls = ["http://mirrors.ustc.edu.cn/golang/{}"],
    sdks = {
        "linux_amd64":   ("go1.12.5.linux-amd64.tar.gz",
	        "aea86e3c73495f205929cfebba0d63f1382c8ac59be081b6351681415f4063cf"),
        "darwin_amd64":  ("go1.12.5.darwin-amd64.tar.gz",
            "566d0b407f7d4aa5a1315988b562bbe4e9422a93ce2fbf27a664cddcb9a3e617"),
        "windows_amd64": ("go1.12.5.windows-amd64.zip",
            "ccb694279aab39fe0e70629261f13b0307ee40d2d5e1138ed94738023ab04baa"),
    },
)

go_rules_dependencies()

go_register_toolchains()

gazelle_dependencies()