config = {
  :image          => 'bashtoni/centos7-vagrant',
}

nodes = [
  {
    :name => 'node1',
    :image      => config[:image],
    :ip       => '192.168.56.111'
  }
]

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |d|
    d.image = "mcwarman/vagrant-provider:alpine"
  end
end