config = {
  :image          => 'liz2019/centos7-vagrant-docker:v1',
}

nodes = [
  {
    :name => 'node1',
    :image      => config[:image],
    :ip       => '192.168.56.111'
  },{
    :name => 'node2',
    :image      => config[:image],
    :ip       => '192.168.56.112'
  },{
    :name => 'node3',
    :image      => config[:image],
    :ip       => '192.168.56.113'
   }
]

Vagrant.configure("2") do |cfg|
  ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'
  nodes.each do |node|
   cfg.vm.define node[:name] do |node_config|
      node_config.vm.provider "docker" do |v|
        v.name = node[:name]
        v.has_ssh = true
        # v.build_dir = node[:image]
        v.image = node[:image]
       end
      node_config.vm.provision "file", run: "always", source: "../authorized_keys", destination: "/tmp/authorized_keys"
      node_config.vm.provision "shell", run: "always", inline: <<-SHELL
          mkdir -p /root/.ssh/ && cat /tmp/authorized_keys > /root/.ssh/authorized_keys
      SHELL
       node_config.vm.host_name = node[:name]
       node_config.vm.network :private_network, ip: node[:ip]
    end
  end
end